# ============================= AbSplice-DNA related ================================

# specify genome version hg19 or hg38 
genome: hg19

# store all the vcf file that you want to analyze to directory ../data/resources/vcf_files/
vcf: ../data/resources/analysis_files/vcf_files/{vcf_id}

# parameters for variant filtering
variant_filtering:
  minor_allele_frequency: 
    apply_filter: True
    filter_cutoff: 0.001
  max_num_samples: 
    apply_filter: True
    filter_cutoff: 2

# False by default, you can change this if you want to run on large datasets (see Readme)
use_rocksdb: False

splicemap_tissues:
  # - Adipose_Subcutaneous
  # - Adipose_Visceral_Omentum
  # - Adrenal_Gland
  # - Artery_Aorta
  # - Artery_Coronary
  # - Artery_Tibial
  # - Brain_Amygdala
  # - Brain_Anterior_cingulate_cortex_BA24
  # - Brain_Caudate_basal_ganglia
  # - Brain_Cerebellar_Hemisphere
  # - Brain_Cerebellum
  - Brain_Cortex
  # - Brain_Frontal_Cortex_BA9
  # - Brain_Hippocampus
  # - Brain_Hypothalamus
  # - Brain_Nucleus_accumbens_basal_ganglia
  # - Brain_Putamen_basal_ganglia
  # - Brain_Spinal_cord_cervical_c_1
  # - Brain_Substantia_nigra
  # - Breast_Mammary_Tissue
  # - Cells_Cultured_fibroblasts
  # - Cells_EBV_transformed_lymphocytes
  # - Colon_Sigmoid
  # - Colon_Transverse
  # - Esophagus_Gastroesophageal_Junction
  # - Esophagus_Mucosa
  # - Esophagus_Muscularis
  # - Heart_Atrial_Appendage
  # - Heart_Left_Ventricle
  # - Kidney_Cortex
  # - Liver
  # - Lung
  # - Minor_Salivary_Gland
  # - Muscle_Skeletal
  # - Nerve_Tibial
  # - Ovary
  # - Pancreas
  # - Pituitary
  # - Prostate
  # - Skin_Not_Sun_Exposed_Suprapubic
  # - Skin_Sun_Exposed_Lower_leg
  # - Small_Intestine_Terminal_Ileum
  # - Spleen
  # - Stomach
  # - Testis
  # - Thyroid
  # - Uterus
  # - Vagina
  # - Whole_Blood


# ============================= AbSplice-RNA related ================================

AbSplice_RNA: True

DROP:
    geneAnnotation: 'v29'
    DROP_group: 
      - 'Cells_Cultured_fibroblasts'
    working_dir: ../data/resources/analysis_files/absplice_rna_related_files/DROP/
    sample_annotation: processed_data/aberrant_splicing/annotations/{tissue_cat}.tsv
    count_table: processed_data/aberrant_splicing/datasets/
    outliers: processed_results/aberrant_splicing/results/{geneAnnotation}/


cat_outlier_filtering:
  padjustGene_cutoff: 0.1
  padjust_junction_cutoff: 0.05
  totalCounts_cutoff: 20
  delta_psi_cutoff: 0.3
  outlier_type: 'psi5__psi3__theta'
